<?php

$pages = array(
	"Template:Meeting" => "Template/Meeting.mediawiki",
	"Template:Meeting minutes" => "Template/Meeting minutes.mediawiki",
	"Template:Topic from meeting" => "Template/Topic from meeting.mediawiki",
	"Template:Meeting Minutes Block" => "Template/Meeting Minutes Block.mediawiki",
	"Template:Meeting Minutes Block info for table row" => "Template/Meeting Minutes Block info for table row.mediawiki",
	"Template:Meeting Minutes Block info for table row highlighted" => "Template/Meeting Minutes Block info for table row highlighted.mediawiki",
	"Template:Meeting references row" => "Template/Meeting references row.mediawiki",
	"Template:File link" => "Template/File link.mediawiki",
	"Template:Meeting Minutes/Files" => "Template/Meeting Minutes Files.mediawiki",
	"Template:Collapsible" => "Template/Collapsible.mediawiki",
	"Template:TOC" => "Template/TOC.mediawiki",
	"Template:Meeting Minutes/Table of Recent" => "Template/Meeting Minutes--Table of Recent.mediawiki",
	"Template:Meeting info for table row" => "Template/Meeting info for table row.mediawiki",
	"Template:Meeting info for table row highlighted" => "Template/Meeting info for table row highlighted.mediawiki",
	"Template:Meeting topic and synopsis bullet" => "Template/Meeting topic and synopsis bullet.mediawiki",
	"Template:Meeting Minutes/Related Articles Block" => "Template/Meeting Minutes--Related Articles Block.mediawiki",

	"Category:Meeting" => "Category/Meeting.mediawiki",
	"Category:Meeting Minutes" => "Category/Meeting Minutes.mediawiki",

	"Form:Meeting" => "Form/Meeting.mediawiki",
	"Form:Meeting Minutes" => "Form/Meeting Minutes.mediawiki",

	"Property:Call in number" => "Property/Call in number.mediawiki",
	"Property:Call in password" => "Property/Call in password.mediawiki",
	"Property:Managed by cadre" => "Property/Managed by cadre.mediawiki",
	"Property:Standard day" => "Property/Standard day.mediawiki",
	"Property:Standard time" => "Property/Standard time.mediawiki",
	"Property:Meeting date" => "Property/Meeting date.mediawiki",
	"Property:Meeting type" => "Property/Meeting type.mediawiki",
	"Property:Notes taken by" => "Property/Notes taken by.mediawiki",
	"Property:Start time" => "Property/Start time.mediawiki",
	"Property:From page" => "Property/From page.mediawiki",
	"Property:Has date" => "Property/Has date.mediawiki",
	"Property:Has topic title" => "Property/Has topic title.mediawiki",
	"Property:Index" => "Property/Index.mediawiki",
	"Property:Related article" => "Property/Related article.mediawiki",
	"Property:Synopsis" => "Property/Synopsis.mediawiki",
	"Property:Building" => "Property/Building.mediawiki",
	"Property:Notable attendee" => "Property/Notable attendee.mediawiki",
	"Property:Overview" => "Property/Overview.mediawiki",
	"Property:Room" => "Property/Room.mediawiki",
);